app:
    name: nginx
    group: app
    namespace:
        - easycoop
    container:
      image: nginx
      port: 80
      imagePullSecrets: easycoopreg
      envFrom:
        - configMapRef:
            name: docker-engine-loan-config
        